language: ruby
sudo: required
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.bundle
rvm:
  - 2.3.0
  - 2.2.4
  - rubinius
  - jruby-head
before_install:
  - PATH="/usr/lib/ccache:$PATH" # enable ccache
  - ci-scripts/install-libsodium
  - ci-scripts/install-libzmq
  - ci-scripts/install-libczmq
  - export BUNDLE_PATH=$HOME/.bundle # bundle caching
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
