language: ruby
sudo: false
cache:
  directories:
    - $HOME/.ccache
    - $HOME/.bundle
rvm:
  - 2.3.0
  - rubinius
  - jruby-head
before_install:
  - PATH="/usr/lib/ccache:$PATH" # enable ccache
  - export LD_LIBRARY_PATH=$HOME/lib # custom libs (for execution)
  - export LD_RUN_PATH=$HOME/lib # custom libs (for linking)
  - export PKG_CONFIG_PATH="$HOME/lib/pkgconfig:$PKG_CONFIG_PATH" # custom libs (for linking)
  - ci-scripts/install-libsodium
  - ci-scripts/install-libzmq
  - ci-scripts/install-libczmq
  - export BUNDLE_PATH=$HOME/.bundle # bundle caching
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
