language: ruby
cache: bundler
sudo: required
rvm:
  - 2.2.4
  - rubinius
  - jruby-head
before_install:
  - ci-scripts/install-libsodium
  - ci-scripts/install-libzmq
  - ci-scripts/install-libczmq
  - gem install bundler -v 1.10.6
script: bundle exec rake spec
